### ISSUE TITLE
Setting up Code Quality Checks

### ISSUE THREAD

**Issue by gflachs** [gflachs/Template_MAS_LLM#1]
## Motivation

As a software development team member, I want to establish automated code quality checks in our CI/CD pipeline, so that we can ensure our codebase adheres to best practices, maintains high quality, and minimizes bugs before deployment.

## Description

This feature involves integrating code quality tools into our continuous integration/continuous deployment (CI/CD) pipeline. By automating code quality checks, we aim to uphold coding standards and detect issues early in the development process. This will contribute to a more reliable and maintainable codebase, helping to deliver high-quality software faster and with fewer defects.

## Acceptance criteria

Feature: Integration of Code Quality Tools into CI/CD Pipeline

  Scenario: Integrating code quality tools into the CI/CD pipeline
    Given the CI/CD pipeline is set up
    When code quality tools are integrated
    Then code quality checks should be triggered automatically on code pushes or pull requests

  Scenario: Producing actionable reports with code quality issues
    Given a code push or pull request triggers a quality check
    When the code quality tools run
    Then the tools should produce clear, actionable reports highlighting issues like linting errors, code smells, and potential     security vulnerabilities

  Scenario: Notifying developers of code quality issues
    Given code quality issues are identified
    When the quality checks are completed
    Then developers should be notified of any issues found during the checks

  Scenario: Flagging pull requests with critical issues
    Given a pull request contains critical issues or fails code quality checks
    When the quality check is completed
    Then the pull request should be automatically flagged for review or rejection

## Test Criteria

- Attempt to push code that violates defined coding standards to test whether the CI/CD pipeline triggers code quality checks and reports appropriate errors. 
- Push code changes that adhere to standards to ensure that the pipeline successfully passes them without flagging issues. 
- Verify that detailed reports from the code quality tools are generated and accessible to developers. 
- Check notifications to ensure the development team is informed of code quality issues. 
- Submit a pull request with known issues and confirm that it is flagged or rejected as expected according to the code quality thresholds set.

**Comment by AliceKitchkin** [comment]
1. Connect Github to SonarCloud via tokens
4. Create in every project a new branch Set-Up-SonarCloud
5. Create in every project a github action, named build.yml
6. Create in every project a sonar-project.properties file

See here for more information:
https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/ci-based-analysis/github-actions-for-sonarcloud/
https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

**Comment by AliceKitchkin** [comment]
Working hours: 3h
